#!/bin/bash
#NAMESPACE=testing
#@covered-begin
namespaced FAILURES=()
namespaced ASSERTIONS=0
#@covered-end

function assert(expected actual) {
    namespaced ASSERTIONS=`expr ${namespaced ASSERTIONS} + 1`
    if [[ "$expected" != "$actual" ]]
    then
        #@covered-begin tests::testing
        namespaced FAILURES+=("`echo -e "\nAssertion failed: expected '$expected', got '$actual'"; bootstrap_trace;`")
        return $ERROR_BAD_PROGRAMMER
        #@covered-end
    fi
}

function run_tests(namespaces) {
    local test_count=0
    for namespace in $namespaces
    do
        local MODULE=`bootstrap_module_from_namespace "tests::${namespace}"`
        local RETURN=0
        if [[ $MODULE == '' ]]
        then
            #@covered-begin tests::testing::test::no_tests
            echo "No tests found for ${namespace}"
            return $ERROR_BAD_PROGRAMMER
            #@covered-end
        fi
        for mod in $MODULE
        do
            bootstrap_load_module "$mod"
            for func_name in `cat $SCRIPT_DIR/$MODULE_DIR/$mod | grep -i 'Function test::' | cut -d ' ' -f 2`
            do
                tests::${namespace}::$func_name
                local test_count=`expr $test_count + 1`
            done
        done
    done

    if [[ ${#namespaced FAILURES[@]} -gt 0 ]]
    then
        #@covered-begin tests::testing::test::failure
        RETURN=$ERROR_BAD_PROGRAMMER
        echo -e "${namespaced FAILURES[@]}"
        #@covered-end
    fi

    echo "Tests run: [ ${test_count} ], assertions: [ ${namespaced ASSERTIONS} ], failures: [ ${#namespaced FAILURES[@]} ]"
    return $RETURN
}
#@covered-begin
dependencies::register_module "core/testing/tests"
#@covered-end
